<?php
/**
 * Rate Movie block markup.
 *
 * @package TenupBlockTheme
 *
 * @var array    $attributes Block attributes.
 * @var string   $content    Block content.
 * @var WP_Block $block      Block instance.
 */

$trigger_text = esc_html__( 'Rate', 'tenup-block-theme' );
$clear_text   = esc_html__( 'Clear', 'tenup-block-theme' );

/**
 * Note we are using do_blocks() so that we will get
 * block-style-variation-styles-inline-css generated by
 * using the theme/styles/*.json approach to styling.
 *
 * A maybe more practical option for buttons would be to
 * use a CSS file to style variations, but this is a good
 * example of how to work with the theme.json approach
 * if you need block markup from PHP.
 */

$trigger_button = '
<!-- wp:button {"tagName":"button"} -->
<div class="wp-block-button">
	<button
		aria-controls="rate-movie-popover"
		aria-haspopup="true"
		class="wp-block-button__link wp-element-button wp-block-tenup-rate-movie__trigger"
		data-wp-bind--aria-expanded="state.isPopoverOpen"
		data-wp-text="state.buttonText"
		popovertarget="rate-movie-popover"
		type="button"
	>' . $trigger_text . '</button>
</div>
<!-- /wp:button -->
';

$clear_button = '
<!-- wp:button {"tagName":"button","className":"is-style-secondary"} -->
<div class="wp-block-button is-style-secondary">
	<button
		class="wp-block-button__link wp-element-button"
		data-wp-class--is-hidden="!state.hasRating"
		data-wp-on--click="actions.clearRating"
		type="button"
	>' . $clear_text . '</button>
</div>
<!-- /wp:button -->
';

$block_wrapper_attributes = get_block_wrapper_attributes(
	[
		'data-wp-interactive' => 'tenup/rate-movie',
	]
);

?>
<div
	<?php echo $block_wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
	<?php echo wp_interactivity_data_wp_context( [ 'rating' => null ] ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
>

	<?php echo do_blocks( $trigger_button ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>

	<div
		aria-labelledby="rate-movie-popover-label"
		aria-modal="true"
		class="wp-block-tenup-rate-movie__popover"
		data-wp-class--is-open="state.isPopoverOpen"
		data-wp-init="callbacks.initPopover"
		id="rate-movie-popover"
		popover
		role="dialog"
	>
		<div class="wp-block-tenup-rate-movie__popover-content">
			<label
				class="wp-block-tenup-rate-movie__slider"
			>
				<span class="visually-hidden"><?php echo esc_html__( 'Rate this movie from 1 to 10', 'tenup-block-theme' ); ?></span>
				<input
					data-wp-bind--value="state.sliderValue"
					data-wp-on--input="actions.selectRating"
					id="wp-block-tenup-rate-movie-slider"
					max="10"
					min="1"
					step="1"
					type="range"
				/>
			</label>

			<span class="wp-block-tenup-rate-movie__popup-text" data-wp-text="state.popupRatingText"></span>

			<?php echo do_blocks( $clear_button ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>

		</div>
	</div>
</div>
